export const GET_RED_COLOR_FOR_TEXT = "GET_RED_COLOR_FOR_TEXT";
export const GET_GREEN_COLOR_FOR_TEXT = "GET_GREEN_COLOR_FOR_TEXT";
export const GET_BLUE_COLOR_FOR_TEXT = "GET_BLUE_COLOR_FOR_TEXT";
export const GET_TEXT_COLOR = "GET_TEXT_COLOR";

export const GET_RED_COLOR_FOR_BACKGROUND = "GET_RED_COLOR_FOR_BACKGROUND";
export const GET_GREEN_COLOR_FOR_BACKGROUND = "GET_GREEN_COLOR_FOR_BACKGROUND";
export const GET_BLUE_COLOR_FOR_BACKGROUND = "GET_BLUE_COLOR_FOR_BACKGROUND";
export const GET_BACKGROUND_COLOR = "GET_BACKGROUND_COLOR";
