import { ColorContrastReducer } from "./colorContrastReducer";
import {
    GET_RED_COLOR_FOR_TEXT,
    GET_GREEN_COLOR_FOR_TEXT,
    GET_BLUE_COLOR_FOR_TEXT,
    GET_TEXT_COLOR,
    GET_RED_COLOR_FOR_BACKGROUND,
    GET_GREEN_COLOR_FOR_BACKGROUND,
    GET_BLUE_COLOR_FOR_BACKGROUND,
    GET_BACKGROUND_COLOR,
  } from "./colorContrastconstants";

export {
    ColorContrastReducer,
    GET_RED_COLOR_FOR_BACKGROUND,
    GET_BACKGROUND_COLOR,
    GET_BLUE_COLOR_FOR_BACKGROUND,
    GET_BLUE_COLOR_FOR_TEXT,
    GET_GREEN_COLOR_FOR_BACKGROUND,
    GET_GREEN_COLOR_FOR_TEXT,
    GET_RED_COLOR_FOR_TEXT,
    GET_TEXT_COLOR
}